name: MobBounty
main: com.stevenmattera.MobBounty.Main
version: 1.00
website: http://stevenmattera.com
author: Steven Mattera
description: Simple plugin for iConomy that pays players for killing mobs.
commands:
  mb:
    description: View rewards.
    usage: /<command>
  mbreward:
    description: Modify reward amount per mob.
    usage: /<command> <mob> <amount>
    aliases:
      - mbr
  mbmulti:
    description: Modify multiplication amount per world.
    usage: /<command> <world> <amount>
    aliases:
      - mbm